export const SAVE_PRODUCT 				= 'SAVE_PRODUCT';
export const UPLOAD_PROD_FULFILLED 		= 'UPLOAD_PROD_FULFILLED';
export const UPLOAD_PROD_REJECTED 		= 'UPLOAD_PROD_REJECTED';

export const POST_INVENTORY 			= 'POST_INVENTORY';
export const FETCH_INVENTORY 			= 'FETCH_INVENTORY';

export const FETCH_USER 				= 'FETCH_USER';
export const FETCH_USER_FULFILLED 		= 'FETCH_USER_FULFILLED';

export const FETCH_AMOUNT_SUCCESS 		= 'FETCH_AMOUNT_SUCCESS';
export const AMOUNT_IS_LOADING 			= 'AMOUNT_IS_LOADING';


export const CREATE_BOOK_SUCCESS 		= 'CREATE_BOOK_SUCCESS';
export const FETCH_BOOK_SUCCESS 		= 'FETCH_BOOK_SUCCESS';
export const FETCH_BOOK_BY_ID_SUCCESS 	= 'FETCH_BOOK_BY_ID_SUCCESS';

export const ADD_TO_CART_SUCCESS 		= 'ADD_TO_CART_SUCCESS';
export const FETCH_CART_SUCCESS 		= 'FETCH_CART_SUCCESS';

export const VALIDATE 					= 'VALIDATE';