export const POST_INVENTORY 			= 'POST_INVENTORY';
export const POST_PROD_FULFILLED 		= 'UPLOAD_PROD_FULFILLED';
export const POST_PROD_REJECTED 		= 'UPLOAD_PROD_REJECTED';

export const FETCH_INVENTORY 			= 'FETCH_INVENTORY';
export const FETCH_INVENTORY_FULFILLED 	= 'FETCH_INVENTORY_FULFILLED';