export const POST_INVENTORY 			= 'POST_INVENTORY';
export const POST_PROD_FULFILLED 		= 'UPLOAD_PROD_FULFILLED';
export const FETCH_ERROR 				= 'FETCH_ERROR';

export const FETCH_INVENTORY 			= 'FETCH_INVENTORY';
export const FETCH_INVENTORY_FULFILLED 	= 'FETCH_INVENTORY_FULFILLED';

export const DELETE_INVENTORY 			= 'DELETE_INVENTORY';
export const EDIT_INVENTORY 			= 'EDIT_INVENTORY';